FROM node:14

USER node
RUN mkdir -p /home/node/code

# WORKDIR /home/node/code
# COPY --chown=node:node . ./

WORKDIR /home/node/code
COPY --chown=node:node . ./
RUN rm -rf services/backend
RUN yarn install

RUN yarn workspace @javnikonkursi/shared run build

CMD ["yarn", "workspace", "@javnikonkursi/frontend", "run", "start"]
